### ISSUE TITLE
Does not work if trying to access localhost/lazy

### ISSUE THREAD

**Issue by mii9000** [daniele-zurico/webpack-aot#4]
@daniele-zurico  If I go from `localhost/` to `locahost/lazy` by clicking the hyperlink then it works otherwise, if I try to open `localhost/lazy` then it does not work.

**Comment by daniele-zurico** [comment]
It's a server configuration! If you don't want to configure anything you can use html with policy #.
I.e #lazy
Have a look on the doc on angular.io it's just a line to change in the riotModule
